# Importing modules

In [1]:
import numpy as np
from tqdm.notebook import tqdm

In [2]:
class neuralNet(object):
    
    
    def __init__(self,no_of_features):
        
        self.no_of_features = no_of_features
        
        self.synapticWeights = 2* np.random.random((self.no_of_features,1)) -1
        self.output = 0.0
        
    def sigmoid(self,x):
        return 1/(1+np.exp(-x))
    
    def sigmoid_derivative(self,x):
        return x*(1-x)

    
    def train(self,training_inputs,training_outputs,training_iterations):
        
        for i in tqdm(range(training_iterations)):
            
            self.output = self.think(training_inputs)
            #print(output)
            error = training_outputs - self.output
            adjustment = np.dot(training_inputs.T, error*self.sigmoid_derivative(self.output))
            
            self.synapticWeights += adjustment
    
    def think(self, inputs):
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot((inputs),self.synapticWeights))
        return output

In [3]:
arr_inputs = np.array([[0,0,1],
                [1,1,1],
                [1,0,1],
                [0,1,1]
               ])
arr_outputs = np.array([[0,1,1,0]]).T
len(arr_inputs[0])

3

In [4]:
neural_net = neuralNet(len(arr_inputs[0]))

In [5]:
neural_net.synapticWeights

array([[ 0.29984505],
       [-0.48864945],
       [ 0.12691513]])

In [6]:
neural_net.train(arr_inputs,arr_outputs,100000)

In [7]:
neural_net.synapticWeights

array([[12.0086991 ],
       [-0.20450329],
       [-5.80022677]])

In [8]:
neural_net.output

array([[0.00301775],
       [0.99753713],
       [0.99799172],
       [0.002461  ]])